Portfolio/urls.py
"""Portfolio URL Configuration

The `urlpatterns` list routes URLs to user_views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function user_views
    1. Add an import:  from my_app import user_views
    2. Add a URL to urlpatterns:  path('', user_views.home, name='home')
Class-based user_views
    1. Add an import:  from other_app.user_views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .user_views.create_account import CreateAccount
from .user_views.view_account import ViewAccount
from .user_views.profile_view import ProfileView
from django.contrib.auth import views as auth_views


app_name = 'user'
urlpatterns = [
    path('register/', CreateAccount.as_view(), name='register'),
    path('user/', ViewAccount.as_view(), name='user'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name="logout"),
    path('profile/', ProfileView.as_view(), name='profile'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    bio = models.CharField(verbose_name='Bio', blank=True, max_length=30)

    def __str__(self):
        return str(self.id) + 'Bio'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class ProfileImage(models.Model):
    image = models.ImageField(verbose_name='Image', upload_to='profile/images')

    def __str__(self):
        return f'{self.id} Image'

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from user.models import Profile, ProfileImage
from django.contrib.auth.forms import User
from django import forms


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', )


class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = ProfileImage
        fields = ('image', )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=PT+Serif&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

  <title>Gourab Sinha</title>
    {% load static %}
</head>

<body class="bg-light">
  <!-- START HERE -->
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>


  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</body>

</html>

user/templates/user/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary btn-md" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'user:register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock %}

user/templates/user/logout.html
{% extends 'base.html' %}
{% block content %}
    <h2>You logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'user:login' %}">Sign In Again</a>
        </small>
    </div>
{% endblock %}

user/templates/user/profile_image.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="{% url 'user:profile' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
{#                {{ profile_image_form|crispy }}#}
            </fieldset>
            <input type="text" name="Gourab">
            <input type="file" name="image">
            <div class="form-group">
                <button class="btn btn-primary btn-md" type="submit">Upload</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'user:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ user_form|crispy}}
                {{ profile_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary btn-md" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'user:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}

user/templates/user/user.html
{% extends 'base.html' %}
{% block content %}
    <div class="display-2">{{ user.username }}</div>
    <div class="display-2">{{ user.email }}</div>
{% endblock %}